### ISSUE TITLE
Doesn't build with 6.15.0

### ISSUE THREAD

**Issue by flichtenheld** [OpenVPN/ovpn-dco#81]
E.g. on fedora-rawhide:

```
DKMS (dkms-3.1.8) make.log for ovpn-dco/0.2.20241216.2.fc43 for kernel 6.15.0-0.rc3.20250424gita79be02bba5c.31.fc43.x86_64 (x86_64)
Fri Apr 25 12:30:45 UTC 2025

Building module(s)
# command: make -j4 KERNELRELEASE=6.15.0-0.rc3.20250424gita79be02bba5c.31.fc43.x86_64 -C ./ VER=6.15.0-0.rc3.20250424gita79be02bba5c.31.fc43.x86_64 KERNEL_SRC=/lib/modules/6.15.0-0.rc3.20250424gita79be02bba5c.31.fc43.x86_64/build REVISION='ovpn:0.2.20241216.2.fc43'
make: Entering directory '/var/lib/dkms/ovpn-dco/0.2.20241216.2.fc43/build'
/var/lib/dkms/ovpn-dco/0.2.20241216.2.fc43/build/gen-compat-autoconf.sh /var/lib/dkms/ovpn-dco/0.2.20241216.2.fc43/build/compat-autoconf.h
make -C /lib/modules/6.15.0-0.rc3.20250424gita79be02bba5c.31.fc43.x86_64/build M=/var/lib/dkms/ovpn-dco/0.2.20241216.2.fc43/build PWD=/var/lib/dkms/ovpn-dco/0.2.20241216.2.fc43/build REVISION=ovpn:0.2.20241216.2.fc43 CONFIG_OVPN_DCO_V2=m INSTALL_MOD_DIR=updates/	modules
make[1]: Entering directory '/usr/src/kernels/6.15.0-0.rc3.20250424gita79be02bba5c.31.fc43.x86_64'
make[2]: Entering directory '/var/lib/dkms/ovpn-dco/0.2.20241216.2.fc43/build'
  CC [M]  drivers/net/ovpn-dco/main.o
  CC [M]  drivers/net/ovpn-dco/bind.o
  CC [M]  drivers/net/ovpn-dco/crypto.o
  CC [M]  drivers/net/ovpn-dco/ovpn.o
drivers/net/ovpn-dco/main.c:212:35: error: initialization of 'int (*)(struct net_device *, struct rtnl_newlink_params *, struct netlink_ext_ack *)' from incompatible pointer type 'int (*)(struct net *, struct net_device *, struct nlattr **, struct nlattr **, struct netlink_ext_ack *)' [-Wincompatible-pointer-types]
  212 |         .newlink                = ovpn_newlink,
      |                                   ^~~~~~~~~~~~
drivers/net/ovpn-dco/main.c:212:35: note: (near initialization for 'ovpn_link_ops.newlink')
drivers/net/ovpn-dco/main.c:166:12: note: 'ovpn_newlink' declared here
  166 | static int ovpn_newlink(struct net *src_net, struct net_device *dev, struct nlattr *tb[],
      |            ^~~~~~~~~~~~
  CC [M]  drivers/net/ovpn-dco/peer.o
make[5]: *** [/usr/src/kernels/6.15.0-0.rc3.20250424gita79be02bba5c.31.fc43.x86_64/scripts/Makefile.build:203: drivers/net/ovpn-dco/main.o] Error 1
make[5]: *** Waiting for unfinished jobs....
drivers/net/ovpn-dco/peer.c: In function 'ovpn_peer_timer_delete_all':
drivers/net/ovpn-dco/peer.c:194:9: error: implicit declaration of function 'del_timer_sync'; did you mean 'dev_mc_sync'? [-Wimplicit-function-declaration]
  194 |         del_timer_sync(&peer->keepalive_xmit);
      |         ^~~~~~~~~~~~~~
      |         dev_mc_sync
drivers/net/ovpn-dco/peer.c: In function 'ovpn_peer_keepalive_set':
drivers/net/ovpn-dco/peer.c:306:17: error: implicit declaration of function 'del_timer'; did you mean 'add_timer'? [-Wimplicit-function-declaration]
  306 |                 del_timer(&peer->keepalive_xmit);
      |                 ^~~~~~~~~
      |                 add_timer
make[5]: *** [/usr/src/kernels/6.15.0-0.rc3.20250424gita79be02bba5c.31.fc43.x86_64/scripts/Makefile.build:203: drivers/net/ovpn-dco/peer.o] Error 1
make[4]: *** [/usr/src/kernels/6.15.0-0.rc3.20250424gita79be02bba5c.31.fc43.x86_64/scripts/Makefile.build:461: drivers/net/ovpn-dco] Error 2
make[3]: *** [/usr/src/kernels/6.15.0-0.rc3.20250424gita79be02bba5c.31.fc43.x86_64/Makefile:2057: .] Error 2
make[2]: *** [/usr/src/kernels/6.15.0-0.rc3.20250424gita79be02bba5c.31.fc43.x86_64/Makefile:260: __sub-make] Error 2
make[2]: Leaving directory '/var/lib/dkms/ovpn-dco/0.2.20241216.2.fc43/build'
make[1]: *** [Makefile:260: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/kernels/6.15.0-0.rc3.20250424gita79be02bba5c.31.fc43.x86_64'
make: *** [Makefile:51: all] Error 2
make: Leaving directory '/var/lib/dkms/ovpn-dco/0.2.20241216.2.fc43/build'
```

**Comment by rubin55** [comment]
Same on Gentoo, see: https://bugs.gentoo.org/956714

**Comment by rubin55** [comment]
OpenSuSE seems to have a patch for this according to rpmfind: https://rpmfind.net/linux/RPM/opensuse/tumbleweed/x86_64/ovpn-dco-kmp-default-0.2.20241216~git0.a08b2fd_k6.15.0_1-3.5.x86_64.html

Note `use-new-timer-api.patch` and `6.15-newlink-proto.patch` mentioned there.
