### ISSUE TITLE
Does not build on kernel < 6.4.10, net/gso.h: No such file or directory

### ISSUE THREAD

**Issue by bernhardschmidt** [OpenVPN/ovpn-dco#44]
Commit dba96d203f960356b477291d6a58d30fc096fbe4 for #42 broke compilation for kernels < 6.4.10

```
  CC [M]  /var/lib/dkms/ovpn-dco/0.0+git20230816/build/drivers/net/ovpn-dco/tcp.o
  CC [M]  /var/lib/dkms/ovpn-dco/0.0+git20230816/build/drivers/net/ovpn-dco/udp.o
/var/lib/dkms/ovpn-dco/0.0+git20230816/build/drivers/net/ovpn-dco/ovpn.c:25:10: fatal error: net/gso.h: No such file or directory
   25 | #include <net/gso.h>
      |          ^~~~~~~~~~~
compilation terminated.
```

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1050211

**Comment by ordex** [comment]
Mh, maybe I forgot to commit a piece of the change..
Thanks for the report, let me check

**Comment by ordex** [comment]
Just compiled against a couple of v6.3.x kernels and it just worked.
@bernhardschmidt please have a look at the commit https://github.com/OpenVPN/ovpn-dco/commit/dba96d203f960356b477291d6a58d30fc096fbe4 in full, as it changes the Makefile and introduces a new folder. Maybe something is required in the packaging in order to include those as well?

**Comment by bernhardschmidt** [comment]
*sigh* I'm getting old :-(

Thanks for the hint.
