### ISSUE TITLE
Doesn't build with 5.14.0-570.16.1.el9_6 (RHEL9)

### ISSUE THREAD

**Issue by uddr** [OpenVPN/ovpn-dco#83]
```
# command: make -j4 KERNELRELEASE=5.14.0-570.16.1.el9_6.x86_64 -C ./ VER=5.14.0-570.16.1.el9_6.x86_64 KERNEL_SRC=/lib/modules/5.14.0-570.16.1.el9_6.x86_64/build REVISION='ovpn:0.2.20241216.2.el9'
make: Entering directory '/var/lib/dkms/ovpn-dco/0.2.20241216.2.el9/build'
/var/lib/dkms/ovpn-dco/0.2.20241216.2.el9/build/gen-compat-autoconf.sh /var/lib/dkms/ovpn-dco/0.2.20241216.2.el9/build/compat-autoconf.h
make -C /lib/modules/5.14.0-570.16.1.el9_6.x86_64/build M=/var/lib/dkms/ovpn-dco/0.2.20241216.2.el9/build PWD=/var/lib/dkms/ovpn-dco/0.2.20241216.2.el9/build REVISION=ovpn:0.2.20241216.2.el9 CONFIG_OVPN_DCO_V2=m INSTALL_MOD_DIR=updates/	modules
make[1]: Entering directory '/usr/src/kernels/5.14.0-570.16.1.el9_6.x86_64'
  CC [M]  /var/lib/dkms/ovpn-dco/0.2.20241216.2.el9/build/drivers/net/ovpn-dco/main.o
  CC [M]  /var/lib/dkms/ovpn-dco/0.2.20241216.2.el9/build/drivers/net/ovpn-dco/bind.o
  CC [M]  /var/lib/dkms/ovpn-dco/0.2.20241216.2.el9/build/drivers/net/ovpn-dco/crypto.o
  CC [M]  /var/lib/dkms/ovpn-dco/0.2.20241216.2.el9/build/drivers/net/ovpn-dco/ovpn.o
In file included from <command-line>:
./include/linux/skbuff.h: In function 'skb_needs_linearize':
/var/lib/dkms/ovpn-dco/0.2.20241216.2.el9/build/linux-compat.h:66:37: error: 'NETIF_F_LLTX' undeclared (first use in this function); did you mean 'NETIF_F_LRO'?
   66 | #define NETIF_F_SG (__NETIF_F(SG) | NETIF_F_LLTX)
      |                                     ^~~~~~~~~~~~
./include/linux/skbuff.h:4044:60: note: in expansion of macro 'NETIF_F_SG'
 4044 |                 (skb_shinfo(skb)->nr_frags && !(features & NETIF_F_SG)));
      |                                                            ^~~~~~~~~~
/var/lib/dkms/ovpn-dco/0.2.20241216.2.el9/build/linux-compat.h:66:37: note: each undeclared identifier is reported only once for each function it appears in
   66 | #define NETIF_F_SG (__NETIF_F(SG) | NETIF_F_LLTX)
      |                                     ^~~~~~~~~~~~
./include/linux/skbuff.h:4044:60: note: in expansion of macro 'NETIF_F_SG'
 4044 |                 (skb_shinfo(skb)->nr_frags && !(features & NETIF_F_SG)));
      |                                                            ^~~~~~~~~~
In file included from <command-line>:
./include/linux/skbuff.h: In function 'skb_needs_linearize':
/var/lib/dkms/ovpn-dco/0.2.20241216.2.el9/build/linux-compat.h:66:37: error: 'NETIF_F_LLTX' undeclared (first use in this function); did you mean 'NETIF_F_LRO'?
   66 | #define NETIF_F_SG (__NETIF_F(SG) | NETIF_F_LLTX)
      |                                     ^~~~~~~~~~~~
./include/linux/skbuff.h:4044:60: note: in expansion of macro 'NETIF_F_SG'
 4044 |                 (skb_shinfo(skb)->nr_frags && !(features & NETIF_F_SG)));
      |                                                            ^~~~~~~~~~
/var/lib/dkms/ovpn-dco/0.2.20241216.2.el9/build/linux-compat.h:66:37: note: each undeclared identifier is reported only once for each function it appears in
   66 | #define NETIF_F_SG (__NETIF_F(SG) | NETIF_F_LLTX)
      |                                     ^~~~~~~~~~~~
./include/linux/skbuff.h:4044:60: note: in expansion of macro 'NETIF_F_SG'
 4044 |                 (skb_shinfo(skb)->nr_frags && !(features & NETIF_F_SG)));
      |                                                            ^~~~~~~~~~
In file included from <command-line>:
./include/linux/skbuff.h: In function 'skb_needs_linearize':
/var/lib/dkms/ovpn-dco/0.2.20241216.2.el9/build/linux-compat.h:66:37: error: 'NETIF_F_LLTX' undeclared (first use in this function); did you mean 'NETIF_F_LRO'?
   66 | #define NETIF_F_SG (__NETIF_F(SG) | NETIF_F_LLTX)
      |                                     ^~~~~~~~~~~~
./include/linux/skbuff.h:4044:60: note: in expansion of macro 'NETIF_F_SG'
 4044 |                 (skb_shinfo(skb)->nr_frags && !(features & NETIF_F_SG)));
      |                                                            ^~~~~~~~~~
/var/lib/dkms/ovpn-dco/0.2.20241216.2.el9/build/linux-compat.h:66:37: note: each undeclared identifier is reported only once for each function it appears in
   66 | #define NETIF_F_SG (__NETIF_F(SG) | NETIF_F_LLTX)
      |                                     ^~~~~~~~~~~~
./include/linux/skbuff.h:4044:60: note: in expansion of macro 'NETIF_F_SG'
 4044 |                 (skb_shinfo(skb)->nr_frags && !(features & NETIF_F_SG)));
      |                                                            ^~~~~~~~~~
In file included from ./include/net/sock.h:46,
                 from ./include/linux/tcp.h:19,
                 from ./include/linux/ipv6.h:112,
                 from /var/lib/dkms/ovpn-dco/0.2.20241216.2.el9/build/drivers/net/ovpn-dco/main.h:14,
                 from /var/lib/dkms/ovpn-dco/0.2.20241216.2.el9/build/drivers/net/ovpn-dco/ovpn.c:10:
./include/linux/netdevice.h: At top level:
./include/linux/netdevice.h:2379:14: error: duplicate member 'needs_free_netdev'
 2379 |         bool needs_free_netdev;
      |              ^~~~~~~~~~~~~~~~~
In file included from <command-line>:
./include/linux/skbuff.h: In function 'skb_needs_linearize':
/var/lib/dkms/ovpn-dco/0.2.20241216.2.el9/build/linux-compat.h:66:37: error: 'NETIF_F_LLTX' undeclared (first use in this function); did you mean 'NETIF_F_LRO'?
   66 | #define NETIF_F_SG (__NETIF_F(SG) | NETIF_F_LLTX)
      |                                     ^~~~~~~~~~~~
./include/linux/skbuff.h:4044:60: note: in expansion of macro 'NETIF_F_SG'
 4044 |                 (skb_shinfo(skb)->nr_frags && !(features & NETIF_F_SG)));
      |                                                            ^~~~~~~~~~
/var/lib/dkms/ovpn-dco/0.2.20241216.2.el9/build/linux-compat.h:66:37: note: each undeclared identifier is reported only once for each function it appears in
   66 | #define NETIF_F_SG (__NETIF_F(SG) | NETIF_F_LLTX)
      |                                     ^~~~~~~~~~~~
./include/linux/skbuff.h:4044:60: note: in expansion of macro 'NETIF_F_SG'
 4044 |                 (skb_shinfo(skb)->nr_frags && !(features & NETIF_F_SG)));
      |                                                            ^~~~~~~~~~
In file included from ./include/net/sock.h:46,
                 from ./include/linux/tcp.h:19,
                 from ./include/linux/ipv6.h:112,
                 from /var/lib/dkms/ovpn-dco/0.2.20241216.2.el9/build/drivers/net/ovpn-dco/main.h:14,
                 from /var/lib/dkms/ovpn-dco/0.2.20241216.2.el9/build/drivers/net/ovpn-dco/crypto.c:10:
./include/linux/netdevice.h: At top level:
./include/linux/netdevice.h:2379:14: error: duplicate member 'needs_free_netdev'
 2379 |         bool needs_free_netdev;
      |              ^~~~~~~~~~~~~~~~~
In file included from ./include/net/sock.h:46,
                 from ./include/linux/tcp.h:19,
                 from ./include/linux/ipv6.h:112,
                 from /var/lib/dkms/ovpn-dco/0.2.20241216.2.el9/build/drivers/net/ovpn-dco/main.h:14,
                 from /var/lib/dkms/ovpn-dco/0.2.20241216.2.el9/build/drivers/net/ovpn-dco/ovpn.h:13,
                 from /var/lib/dkms/ovpn-dco/0.2.20241216.2.el9/build/drivers/net/ovpn-dco/bind.c:10:
./include/linux/netdevice.h: At top level:
./include/linux/netdevice.h:2379:14: error: duplicate member 'needs_free_netdev'
 2379 |         bool needs_free_netdev;
      |              ^~~~~~~~~~~~~~~~~
In file included from ./include/net/sock.h:46,
                 from ./include/linux/tcp.h:19,
                 from ./include/linux/ipv6.h:112,
                 from /var/lib/dkms/ovpn-dco/0.2.20241216.2.el9/build/drivers/net/ovpn-dco/main.h:14,
                 from /var/lib/dkms/ovpn-dco/0.2.20241216.2.el9/build/drivers/net/ovpn-dco/main.c:10:
./include/linux/netdevice.h: At top level:
./include/linux/netdevice.h:2379:14: error: duplicate member 'needs_free_netdev'
 2379 |         bool needs_free_netdev;
      |              ^~~~~~~~~~~~~~~~~
make[3]: *** [scripts/Makefile.build:249: /var/lib/dkms/ovpn-dco/0.2.20241216.2.el9/build/drivers/net/ovpn-dco/ovpn.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: *** [scripts/Makefile.build:249: /var/lib/dkms/ovpn-dco/0.2.20241216.2.el9/build/drivers/net/ovpn-dco/crypto.o] Error 1
make[3]: *** [scripts/Makefile.build:249: /var/lib/dkms/ovpn-dco/0.2.20241216.2.el9/build/drivers/net/ovpn-dco/bind.o] Error 1
In file included from <command-line>:
./include/linux/if_vlan.h: In function 'vlan_features_check':
/var/lib/dkms/ovpn-dco/0.2.20241216.2.el9/build/linux-compat.h:66:37: error: 'NETIF_F_LLTX' undeclared (first use in this function); did you mean 'NETIF_F_LRO'?
   66 | #define NETIF_F_SG (__NETIF_F(SG) | NETIF_F_LLTX)
      |                                     ^~~~~~~~~~~~
./include/linux/if_vlan.h:770:29: note: in expansion of macro 'NETIF_F_SG'
  770 |                 features &= NETIF_F_SG | NETIF_F_HIGHDMA | NETIF_F_HW_CSUM |
      |                             ^~~~~~~~~~
/var/lib/dkms/ovpn-dco/0.2.20241216.2.el9/build/drivers/net/ovpn-dco/main.c: In function 'ovpn_setup':
/var/lib/dkms/ovpn-dco/0.2.20241216.2.el9/build/linux-compat.h:66:37: error: 'NETIF_F_LLTX' undeclared (first use in this function); did you mean 'NETIF_F_LRO'?
   66 | #define NETIF_F_SG (__NETIF_F(SG) | NETIF_F_LLTX)
      |                                     ^~~~~~~~~~~~
/var/lib/dkms/ovpn-dco/0.2.20241216.2.el9/build/drivers/net/ovpn-dco/main.c:130:34: note: in expansion of macro 'NETIF_F_SG'
  130 |         netdev_features_t feat = NETIF_F_SG | NETIF_F_HW_CSUM | NETIF_F_RXCSUM |
      |                                  ^~~~~~~~~~
make[3]: *** [scripts/Makefile.build:249: /var/lib/dkms/ovpn-dco/0.2.20241216.2.el9/build/drivers/net/ovpn-dco/main.o] Error 1
make[2]: *** [scripts/Makefile.build:478: /var/lib/dkms/ovpn-dco/0.2.20241216.2.el9/build/drivers/net/ovpn-dco] Error 2
make[1]: *** [Makefile:1947: /var/lib/dkms/ovpn-dco/0.2.20241216.2.el9/build] Error 2
make[1]: Leaving directory '/usr/src/kernels/5.14.0-570.16.1.el9_6.x86_64'
make: *** [Makefile:51: all] Error 2
```

**Comment by ordex** [comment]
@uddr what is the first RHEL version that is hitting this issue? RHEL9.6?

**Comment by uddr** [comment]
@ordex probably yes,
the previous build in April 29 was successful with `5.14.0-503.38.1.el9_5` kernel

**Comment by dsommers** [comment]
@ordex RHEL 9.6 was released about a week ago (my production boxes got it May 13).  `kernel-5.14.0-570.12.1.el9_6.x86_64` was the first one which broke.  The latest kernel update arrived today, `kernel-5.14.0-570.17.1.el9_6.x86_64`

**Comment by ordex** [comment]
commit ed8e85b8dc234c7aea32d9fcee229ecf2dbad389 should fix this.
Can you guys test? If it works, I already tagged it with v0.2.20250520 so that it can be released.

**Comment by dsommers** [comment]
@ordex Yes, that works!

**Comment by ordex** [comment]
I am closing this. @uddr @flichtenheld feel free to package the last tag.
