### ISSUE TITLE
Build error with kernel > 7.1.5

### ISSUE THREAD

**Issue by bernhardschmidt** [OpenVPN/ovpn-dco#103]
Reported in Debian as https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1142917 , I'm just forwarding it.

There is also a patch proposed there.

Original report here:

After a system upgrade today, openvpn-dco-dkms failed to build against
the newly installed kernel with headers from the
linux-headers-7.1.5+deb14-amd64 package. It looks like the interface to
setup_udp_tunnel_sock has changed, with the second argument now being a
"struct sock *" instead of a "struct socket *", as per
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/diff/include/net/udp_tunnel.h?id=v7.1.5&id2=v7.1.4

Here's the build log that backs that up:

```
--- Build log start ---
DKMS (dkms-3.2.2) make.log for ovpn-dco/0.0+git20260519 for kernel 7.1.5+deb14-amd64 (x86_64)
Tue 28 Jul 07:17:39 BST 2026

Building module(s)
# command: make -j4 KERNELRELEASE=7.1.5+deb14-amd64 VER=7.1.5+deb14-amd64 KERNEL_SRC=/lib/modules/7.1.5+deb14-amd64/build REVISION=0.0+git20260519
/var/lib/dkms/ovpn-dco/0.0+git20260519/build/gen-compat-autoconf.sh /var/lib/dkms/ovpn-dco/0.0+git20260519/build/compat-autoconf.h
make -C /lib/modules/7.1.5+deb14-amd64/build M=/var/lib/dkms/ovpn-dco/0.0+git20260519/build PWD=/var/lib/dkms/ovpn-dco/0.0+git20260519/build REVISION=0.0+git20260519 CONFIG_OVPN_DCO_V2=m INSTALL_MOD_DIR=updates/     modules
make[1]: Entering directory '/usr/src/linux-headers-7.1.5+deb14-amd64'
make[2]: Entering directory '/var/lib/dkms/ovpn-dco/0.0+git20260519/build'
  CC [M]  drivers/net/ovpn-dco/main.o
  CC [M]  drivers/net/ovpn-dco/bind.o
  CC [M]  drivers/net/ovpn-dco/crypto.o
  CC [M]  drivers/net/ovpn-dco/ovpn.o
  CC [M]  drivers/net/ovpn-dco/peer.o
  CC [M]  drivers/net/ovpn-dco/sock.o
  CC [M]  drivers/net/ovpn-dco/stats.o
  CC [M]  drivers/net/ovpn-dco/netlink.o
  CC [M]  drivers/net/ovpn-dco/crypto_aead.o
  CC [M]  drivers/net/ovpn-dco/pktid.o
  CC [M]  drivers/net/ovpn-dco/tcp.o
  CC [M]  drivers/net/ovpn-dco/udp.o
drivers/net/ovpn-dco/udp.c: In function ‘ovpn_udp_socket_attach’:
drivers/net/ovpn-dco/udp.c:346:51: error: passing argument 2 of ‘setup_udp_tunnel_sock’ from incompatible pointer type [-Wincompatible-pointer-types]
  346 |         setup_udp_tunnel_sock(sock_net(sock->sk), sock, &cfg);
      |                                                   ^~~~
      |                                                   |
      |                                                   struct socket *
In file included from drivers/net/ovpn-dco/udp.c:25:
/usr/src/linux-headers-7.1.5+deb14-common/include/net/udp_tunnel.h:97:58: note: expected ‘struct sock *’ but argument is of type ‘struct socket *’
   97 | void setup_udp_tunnel_sock(struct net *net, struct sock *sk,
      |                                             ~~~~~~~~~~~~~^~
drivers/net/ovpn-dco/udp.c: In function ‘ovpn_udp_socket_detach’:
drivers/net/ovpn-dco/udp.c:356:51: error: passing argument 2 of ‘setup_udp_tunnel_sock’ from incompatible pointer type [-Wincompatible-pointer-types]
  356 |         setup_udp_tunnel_sock(sock_net(sock->sk), sock, &cfg);
      |                                                   ^~~~
      |                                                   |
      |                                                   struct socket *
/usr/src/linux-headers-7.1.5+deb14-common/include/net/udp_tunnel.h:97:58: note: expected ‘struct sock *’ but argument is of type ‘struct socket *’
   97 | void setup_udp_tunnel_sock(struct net *net, struct sock *sk,
      |                                             ~~~~~~~~~~~~~^~
make[5]: *** [/usr/src/linux-headers-7.1.5+deb14-common/scripts/Makefile.build:294: drivers/net/ovpn-dco/udp.o] Error 1
make[4]: *** [/usr/src/linux-headers-7.1.5+deb14-common/scripts/Makefile.build:553: drivers/net/ovpn-dco] Error 2
make[3]: *** [/usr/src/linux-headers-7.1.5+deb14-common/Makefile:2186: .] Error 2
make[2]: *** [/usr/src/linux-headers-7.1.5+deb14-common/Makefile:260: __sub-make] Error 2
make[2]: Leaving directory '/var/lib/dkms/ovpn-dco/0.0+git20260519/build'
make[1]: *** [/usr/src/linux-headers-7.1.5+deb14-common/Makefile:260: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-7.1.5+deb14-amd64'
make: *** [Makefile:51: all] Error 2

# exit code: 2
# elapsed time: 00:00:04
--- Build log end ---
```

The solution feels like passing in sock->sk would do the trick if
compiling for >=7.1.5. I've tried this locally, and it seems to work.
I've attached the patch, but as I'm not a seasoned kernel developer it
might need a bit of cleaning or, or there could be better ways to do it,
but at least it unambiguously shows the path to the fix.

**Comment by ordex** [comment]
Thanks for reporting! People should likely switch to a more modern OpenVPN if they are running such a modern kernel :)
But the fix should be easy enough.

**Comment by bernhardschmidt** [comment]
I agree :-)

However later in the Debian bug someone else chimed in that openvpn3 still uses ovpn-dco-v2 on all released versions. So while I was ready to drop it from Debian testing/unstable, it's still needed.

**Comment by ordex** [comment]
@bernhardschmidt you mentioned a patch: where can I find it?

**Comment by bernhardschmidt** [comment]
It's attached to the bug report

https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;bug=1142917;filename=interface-7.1.5.patch;msg=5

**Comment by ordex** [comment]
I created a commit in the `fix-7.1.5` branch. Any chance you could give it a go?

I will run some extra tests later today/tomorrow.

Thanks!

**Comment by ordex** [comment]
I just pushed the final fix dc2a2dbd56a8 to `master` and created the tag `v0.2.20260804`.
Thanks again for reporting!

**Comment by bernhardschmidt** [comment]
Unfortunately it doesn't build in 7.1.3 anymore

https://ci.debian.net/packages/o/openvpn-dco-dkms/testing/amd64/74071060/

```
 50s /usr/src/linux-headers-7.1.3+deb14-common/include/net/udp_tunnel.h: At top level:
 50s /var/lib/dkms/ovpn-dco/0.0+git20260519/build/linux-compat.h:51:31: error: conflicting types for ‘ovpn_setup_udp_tunnel_sock’; have ‘void(struct net *, struct socket *, struct udp_tunnel_sock_cfg *)’
 50s    51 | #define setup_udp_tunnel_sock ovpn_setup_udp_tunnel_sock
 50s       |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~

```

**Comment by bernhardschmidt** [comment]
Disregard, I see the patch committed to the master branch is slightly differnet. I'll respin my package

**Comment by ordex** [comment]
Yeah the final version was a bit different.
I tested on .4 and .5 and it went fine.

Let me know!
Thanks!
